import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { MainRoutes } from '../models/Routers';
import Layout from '../components/Layout';

// const Home: NextPage = () => {
//   return (
//     <div className="bg-surface text-onSurface h-screen w-screen font-handwritten flex justify-center items-center">
//       <Head>
//         <title>creator</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <div className="flex flex-col items-center gap-8">
//         <h2>find a story to play in</h2>
//         <Link href={MainRoutes.creation}>create a story</Link>
//         <h2>your stories</h2>
//       </div>
//     </div>
//   );
// };

export default function Home() {
  return (
    <div className="h-full flex justify-center items-center">
      <Head>
        <title>creator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center gap-8">
        <h2>find a story to play in</h2>
        <Link href={MainRoutes.creation}>create a story</Link>
        <h2>your stories</h2>
      </div>
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
